### PR TITLE
button font size + padding

### PR DESCRIPTION
**Pull request by mayagao**
@samanpwbb @tristen make button font size slightly smaller? Should we introduce a different font size here? If not i can move this to mapbox addon.

screen shot 2017-01-31 at 11 47 28 am
screen shot 2017-01-31 at 11 47 11 am

### CODE REVIEW

**Comment by samanpwbb** [comment]
Button font size beeds to be left to txt-* classes

**Comment by mayagao** [comment]
per chat let's not make the default more opinionated 🙅🏿

**Comment by tristen** [comment]
@mayagao If we're always resetting the default style because it doesn't work means we should change it! Core components should function well on their own without always requiring overrides. We can still be slightly opinionated; utility classes will still easily override things.

I think we should re-open this pull request? The only change I'd make is to use the variable for the `txt-s` size over a hard `13px` value and to confirm the component still aligns to the pixel grid.

**Comment by samanpwbb** [comment]
> I think we should re-open this pull request? The only change I'd make is to use the variable for the txt-s size over a hard 13px value and to confirm the component still aligns to the pixel grid.

Okay, I am on board with that 👍  – make sure it still aligns to the grid

**Pull request closed without merging**
