### PR TITLE
prepare assembly 1.0.0

### PR DESCRIPTION
**Pull request by samanpwbb**
Awaiting approval from @davidtheclark @tristen @dasulit. Will merge when I get three 👍 .

### CODE REVIEW

**Comment by tristen** [comment]
changelog?

**Comment by samanpwbb** [comment]
> changelog?

fixed!

**Comment by tristen** [comment]
I'm seeing some issues with line height alignment on select elements (bottom heavy)

screen shot 2017-11-17 at 10 47 49 am

Icon container alignment on checkboxes

screen shot 2017-11-17 at 10 53 38 am

We almost always widen the x padding on these buttons

screen shot 2017-11-17 at 10 54 47 am

---

Now that we are using Assembly on a few projects I wonder if its worth auditing what we use and what we don't. Some things that come to mind:

- Animation utilities I doubt are used.
- Considering the size colors take up in the final stylesheet and that Assembly is very extendable to include whatever you want, should Assembly out-of-the-box support fewer? Like do we really need pink, purple & orange in there? Could we strike a balance between orange and yellow for components denoting warning?

**Comment by davidtheclark** [comment]
Closing as stale. We'll of course revisit this.

**Pull request closed without merging**
