### PR TITLE
Lighten gray-faint

### PR DESCRIPTION
**Pull request by dasulit**
Closes https://github.com/mapbox/assembly/issues/791.

I realize I was mistaken in that comment about using `gray-faint` for code backgrounds— those elements use `darken10`, so my concerns are not resolved by just lightening gray faint:

screen shot 2017-06-07 at 12 10 30

@samanpwbb is there a reason not to use `bg-gray-faint` (keeping `bg-lighten10` for the dark theme) for code elements?

### CODE REVIEW

**Comment by samanpwbb** [comment]
> is there a reason not to use bg-gray-faint (keeping bg-lighten10 for the dark theme) for code elements?

For a little more flexibility. By using a semitransparent background, the same effect will work across a range of backgrounds. 

It seems like the best option is to re-introduce darken5 and lighten5, but for _background_ colors only.

**Review by samanpwbb — APPROVED** [review]
Works, looks good. One recommendation: consider renaming the validator functions. `isNotAccessibleForBg` and `isNotAccessible` don't quite do what they sound like they should do.

**Comment by dasulit** [comment]
@samanpwbb You reviewed so fast, I have a few questions!

* Is it incorrect to return null rather than `color === 'black'` for the [accessibility functions](https://github.com/mapbox/assembly/blob/5ab308be0c44e4b4724cce66a59188646b7e4925/scripts/build-color-variants.js#L77-L85)?
* The changelog says: "-faint or -light form elements are no longer available for _any element_," but it looks like we're [actually excluding -faint and -dark (and now darken5/lighten5)](https://github.com/mapbox/assembly/blob/5ab308be0c44e4b4724cce66a59188646b7e4925/scripts/build-color-variants.js#L79) from forms?
* I feel weird about [this line](https://github.com/mapbox/assembly/blob/5ab308be0c44e4b4724cce66a59188646b7e4925/scripts/build-color-variants.js#L568) (and other places following that pattern), am I doing something wrong? Why was the existing check for _not not_ accessible?

**Comment by dasulit** [comment]
My questions have been answered by renaming the function names. Just committed that change:

`isNotAccessibleForBg` => `isNotAccessibleExceptButtons`
`isNotAccessible` => `isNotAccessibleExceptBg`

**Pull request merged**
