### PR TITLE
New IE friendly spinners

### PR DESCRIPTION
**Pull request by dasulit**
A square spinner, which is a pretty big departure from spinner 1.0. It also works fine without a `--dark` modifier.

@samanpwbb does this look cool enough for Assembly? 😕

### CODE REVIEW

**Comment by samanpwbb** [comment]
I liked the old spinners! I find this one a little bit disorienting.

I haven't looked to see how bad IE actually is yet, doing so now.

**Comment by samanpwbb** [comment]
Hm, the shake is pretty prominent. Can we try using SVG?

**Comment by dasulit** [comment]
I'm on it! This was worth a try, but might as well not introduce a new design at this point.

**Comment by dasulit** [comment]
Dang it, I updated to SVGs, but they don't show up in IE11 at all.

**Comment by davidtheclark** [comment]
> they don't show up in IE11 at all.

I'm pretty sure this wasn't the case last time I looked in IE11, so something may have changed. I'll take another look ...

**Comment by dasulit** [comment]
@davidtheclark may you review this when you get a chance?

**Comment by davidtheclark** [comment]
Looks great! I'll merge.

**Pull request merged**
