### PR TITLE
Fix range input IE-focused bugs

### LINKED ISSUE #524: Range dot is off-center in Edge
screen shot 2017-01-04 at 8 41 52 am

### LINKED ISSUE #582: Range input thumbs not colored in IE11
screen shot 2017-01-06 at 5 14 46 pm

They *do* look colorful in Edge.

### LINKED ISSUE #583: Range track has sharp edges in IE11 and Edge
screen shot 2017-01-06 at 5 18 49 pm

### PR DESCRIPTION
**Pull request by davidtheclark**
- Closes #582 by fixing a typo.
- Closes #524 by magic.
- Closes #583 by addressing a little oversight.
- Gives up on #581 so "closes" it by adding a note to the documentation.

@samanpwbb for review.

### CODE REVIEW

**Comment by samanpwbb** [comment]
@davidtheclark could we center range inputs by adding:

```css
.range {
  height: 24px;
  vertical-align: middle;
}

.range--s { 
  height: 18px;
}
```

**Comment by davidtheclark** [comment]
@samanpwbb `vertical-align: middle` only helps if the element it's aligning with also has `vertical-align: middle`. So I'm not sure that's a more robust solution than just recommending vertical centering patterns (whether that's flexbox, or `inline-block align-middle` on the whole row of things).

**Comment by samanpwbb** [comment]
@davidtheclark If you apply `vertical-align: middle` to range inputs and place them inline or inline block alongside text or other inputs, they correctly center themselves – no need for setting `vertical-align: center` on other elements.

**Comment by samanpwbb** [comment]
I looked into centering a little more and I'm having a hard time figuring out why this happens (regardless of whether anything is `inline` or `inline-block`):
screen shot 2017-01-10 at 10 03 56 pm

Also, it seems like the `vertical-align: middle;` rule on the track (in `-moz` and  `-webkit` at least) doesn't do anything.

**Review by samanpwbb — APPROVED** [review]
I think we can merge this as-is and lean on flex alignment... without it, range input baseline alignment is pretty whacky and so I'm a bit dissatisfied with this. I don't see any solutions after experimenting a little. Seems like range inputs do their own thing a little bit WRT display properties and line height.

**Comment by samanpwbb** [comment]
Okay. I give up!

I do have a few pieces of feedback:

- moz range track  is 3px, others are 4px.
- moz thumbs (didn't check ie/edge) should be sized the same as webkit handles (20px/20px instead of 17px/17px), but they need `box-sizing: border-box` to be declared in order for that to work.
- inline / inline block inputs in IE end up positioned higher than in other browsers. Maybe we can live with this. 
- `vertical-align: middle;` doesn't appear to do anything on tracks.

**Comment by davidtheclark** [comment]
I have added a range-wrapping div. This ensures that *across browsers* ranges are the same height as other inputs and are vertically centered. I think this is the way to go.

**Pull request merged**
